version: '3.8'

volumes:
  postgres_volume:

services:
  postgres:
    image: postgres:13.4
    volumes:
      - postgres_volume:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=pass
      - POSTGRES_DB=db

  php:
    build: ./infra/php
    volumes:
      - ./src:/var/www/html

  nginx:
    build: ./infra/nginx
    ports:
      - 80:80
    volumes:
      - ./src:/var/www/html

  redis:
    image: redis:6.2.5
    ports:
      - 6379:6379